name: Publish to npm

on:
  release:
    types: [published]

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Test and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24.5
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Test packages
        run: yarn test

      - name: Setup npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: yarn publish --access public --non-interactive
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
